fetch_settings:
  jobsdb:
    information-technology:
      - automated
      - automation
      - qa
      - quality assurance
      - raspberry
      - software test
      - software testing
      - testing automation
      - uat

  ctgoodjobs:
    all-information-technology:
      - quality assurance
      - qa
      - automated
      - automation
      - raspberry
      - SDLC
      - software test
      - software testing
      - testing automation
      - uat

  # for testing
  test_site:
    test_category:
      - test_keyword1
      - test_keyword2
