const ERROR_RUN_ERROR=-1
const ERROR_FETCH_ERROR=-2

const ERROR_UPDATE_IGNORE_DATABASE = -3
const EXIT_UPDATE_IGNORE_DATABASE=-3

const ERROR_SETUP_NEW_APPLICATION_LETTER = -4

const ERROR_CANNOT_LOOKUP_CATEGORY_ID = -5

module.exports={
  ERROR_FETCH_ERROR,
  ERROR_RUN_ERROR,
  ERROR_UPDATE_IGNORE_DATABASE,
  EXIT_UPDATE_IGNORE_DATABASE,
  ERROR_SETUP_NEW_APPLICATION_LETTER
}