fetch_settings:
  jobsdb:
    information-technology:
      - qa
      - software testing
      - software test
      - uat
      - automation
      - automated
      - testing automation
      - raspberry
      - quality assurance

    # for testing
    test_category:
      - test_keyword1
      - test_keyword2
