fetch_settings:
  jobsdb:
    information-technology:
      - qa
      - automation
      - automated
      - testing automation
      # - raspberry
      # - software testing
      # - quality assurance

    # for testing
    test_category:
      - test_keyword1
      - test_keyword2
